ALTER TABLE "courses"
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP(3);

ALTER TABLE "chapters"
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP(3);

ALTER TABLE "lessons"
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP(3);
